// layout.tsx


import { Inter } from 'next/font/google';
import Navbar from './components/Navbar';
//import "./page.module.css";


const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'My Bakery',
  description: 'Generated by create next app',
  icons:{
    icon: '/favicon.ico',
  }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
